# Generated by Django 4.0.4 on 2022-04-15 23:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('city', models.CharField(max_length=60, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('publication_date', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Запас')),
                ('image', models.ImageField(upload_to='books_img', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('description', models.CharField(max_length=300, verbose_name='Аннотация')),
                ('existence', models.BooleanField(verbose_name='Наличие')),
                ('authors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author', verbose_name='Автор')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.publisher', verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
